---
title: "interrupted_time_series"
author: "Jueun Park"
date: "2024-11-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(tidyr)
library(ggthemes)
library(lubridate) #date
library(purrr)
library(stargazer)
library(broom)
```


#ITS

##ITS dataset
```{r message=FALSE, warning=FALSE}
hate_master <- read.csv("data_created/hate_master.csv")

#complete the dataset with a full year cycle
hate_its_data <- hate_master %>%
  filter(year > 2015 & grepl("asian", bias_desc, ignore.case = TRUE)) %>%
  group_by(year, month, state) %>%
  dplyr::summarize(total_hate_crimes = n(), .groups = "drop") %>%
  select(state, year, month, total_hate_crimes) %>%
  complete(state, year = 2016:2023, month = month.abb, fill = list(total_hate_crimes = 0))

# Convert month names to numbers for easier date manipulation
hate_its_data <- hate_its_data %>%
  mutate(month_num = match(month, month.abb))


hate_its_data <- hate_its_data %>%
  mutate(date = make_date(year, month_num, 1)) %>%
  arrange(state, date)

# Define the intervention date
intervention_date <- ymd("2020-03-01")

# Create time-related variables
hate_its_data <- hate_its_data %>%
  group_by(state) %>%
  mutate(
    time = row_number(),
    intervention = if_else(date >= intervention_date, 1, 0),  # Intervention indicator
    time_since = if_else(intervention == 1, time - min(time[intervention == 1]) + 1, 0)  # Time since intervention
  ) %>%
  ungroup() %>%
  select(-month_num, -date)

# detach("package:plyr", unload = TRUE)
```






```{r message=FALSE, warning=FALSE}
#ITS results for whole states

# Function to run ITS for each state
its_model <- function(data){
  lm_model <- lm(total_hate_crimes ~ time + intervention + time_since, data = data)
}


# Apply the model to each state and collect results
state_models <- hate_its_data %>%
  group_split(state) %>%
  map(~its_model(.x))

names(state_models) <- hate_its_data %>%
  distinct(state) %>%
  pull(state)


stargazer(state_models, 
           type = "html", 
           dep.var.labels = "Total Hate Crimes",
           column.labels = names(state_models), 
           covariate.labels = c("Time", "Intervention", "Time Since Intervention"),
           omit.stat = "all", 
           digits = 3,
           out = "stat_result/ITS_results.html")
```

```{r message=FALSE, warning=FALSE}
# Vulnerable state

its_results <- map_dfr(state_models, ~tidy(.), .id = "state")

#Identify vulnerable states based on significant positive effects
vulnerable_states <- its_results %>%
  filter((term == "intervention" & p.value < 0.05 & estimate > 0) |
         (term == "time_since" & p.value < 0.05),
         state != "Federal") %>%
  distinct(state)


vulnerable_state_models <- state_models[names(state_models) %in% vulnerable_states$state]

# Stargazer table for vulnerable states only
stargazer(vulnerable_state_models, 
          type = "html", 
          dep.var.labels = "Total Hate Crimes",
          column.labels = names(vulnerable_state_models),  
          covariate.labels = c("Time", "Intervention", "Time Since Intervention"),
          omit.stat = "all", 
          digits = 2,
          out = "stat_result/Vulnerable_States_ITS_Results.html") 
```


```{r message=FALSE, warning=FALSE}
# create `vulnerable_state_data`
vulnerable_state_data <- hate_its_data %>%
  filter(state %in% vulnerable_states$state)



plot_counterfactual_facet_adjusted <- function(data) {
  pre_intervention_data <- data %>% filter(intervention == 0)
  

  pre_model <- lm(total_hate_crimes ~ time, data = pre_intervention_data)
  

  data <- data %>%
    mutate(counterfactual = predict(pre_model, newdata = data))
  
  
ggplot(data, aes(x = time)) +
    geom_point(aes(y = total_hate_crimes, color = "Observed"), size = 0.5, alpha = 0.6) +
    geom_line(aes(y = counterfactual, color = "Counterfactual"), size = 0.7) +
    geom_vline(xintercept = min(data$time[data$intervention == 1]), 
               linetype = "dotted", color = "red") +
    labs(title = "Predicted Asian Hate Crime Cases Without COVID",
         x = "Time (Months)", 
         y = "Total Hate Crimes",
         color = "Legend") +
    scale_color_manual(values = c("Observed" = "steelblue", "Counterfactual" = "red")) +
    theme_fivethirtyeight() +
    theme(legend.title = element_blank()) +
    facet_wrap(~ state, scales = "fixed") +
    ylim(0,30) +
    theme(plot.title = element_text(hjust=0.5),
        plot.subtitle = element_text(hjust=0.5))
}


plot_counterfactual_facet_adjusted(vulnerable_state_data)
```
